[package]
name = "hello-cargo"
version = "0.1.0"
authors = ["Tom Busby <tom@busby.ninja>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
